
spring:
    devtools:
        restart:
            trigger-file: .reboot
    activemq:
        # broker-url: tcp://localhost:61616
        in-memory: true
        user: admin
        password: admin

