spring:
    devtools:
        restart:
            trigger-file: .reboot
    activemq:
        # broker-url: tcp://localhost:61616
        in-memory: true
        user: admin
        password: admin
    datasource:
        # primary:
        # @see org.springframework.boot.autoconfigure.jdbc.DataSourceProperties
        # @see org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration.NonEmbeddedConfiguration
        driver-class-name: org.h2.Driver
        url: jdbc:h2:~/.h2/camunda/process-engine;DB_CLOSE_DELAY=-1;MVCC=TRUE;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password: sa
#    jpa:
#        hibernate:
#            ddl-auto: update
